
-- Used SQLite3 for this example

-- table PEOPLE: containing unique ID and corresponding names.
CREATE TABLE PEOPLE (id INTEGER, name VARCHAR);

INSERT INTO PEOPLE VALUES(1, 'A');
INSERT INTO PEOPLE VALUES(2, 'B');
INSERT INTO PEOPLE VALUES(3, 'C');
INSERT INTO PEOPLE VALUES(4, 'D');

-- ADDRESS: containing the history of address information of each ID.
CREATE TABLE ADDRESS (id INTEGER, address VARCHAR);

INSERT INTO ADDRESS VALUES(1, 'address-1-1');
INSERT INTO ADDRESS VALUES(1, 'address-1-2');
INSERT INTO ADDRESS VALUES(2, 'address-2-1');
INSERT INTO ADDRESS VALUES(3, 'address-3-1');
INSERT INTO ADDRESS VALUES(3, 'address-3-2');
INSERT INTO ADDRESS VALUES(3, 'address-3-3');
INSERT INTO ADDRESS VALUES(4, 'address-4-1');
INSERT INTO ADDRESS VALUES(4, 'address-4-2');
INSERT INTO ADDRESS VALUES(4, 'address-4-3');
INSERT INTO ADDRESS VALUES(4, 'address-4-4');
